base:
  config:
    nacos:
      hostname: localhost
      port: 8848
    mysql:
      hostname: localhost
      port: 3306
      username: root
      password: 123
spring:
  application:
    name: provider-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${base.config.mysql.hostname}:${base.config.mysql.port}/mall_ums_admin?useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: ${base.config.mysql.username}
    password: ${base.config.mysql.password}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
dubbo:
  scan:
    base-packages: cn.edu.tsu.provider.service
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://localhost:8848

mybatis:
  type-aliases-package: com.grq.provider.domain
  mapper-locations: classpath:mapper/*.xml