base:
  config:
    nacos:
      hostname: localhost
      port: 8848
    mysql:
      hostname: localhost
      port: 3306
      username: root
      password: 123
spring:
  application:
    name: consumer-oauth2
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://${base.config.mysql.hostname}:${base.config.mysql.port}/mplus_ums_oauth2?useUnicode=true&serverTimezone=Hongkong&characterEncoding=utf-8&useSSL=false
    username: ${base.config.mysql.username}
    password: ${base.config.mysql.password}
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  cloud:
    nacos:
      discovery:
        server-addr: ${base.config.nacos.hostname}:${base.config.nacos.port}



dubbo:
  scan:
    base-packages: cn.edu.tsu.consumer.controller
  protocol:
    name: dubbo
    port: -1
    serialization: kryo
  registry:
    address: nacos://${base.config.nacos.hostname}:${base.config.nacos.port}

consumer:
  oauth2:
    grant_type: password
    client_id: client
    client_secret: secret
server:
  port: 9002
